### ADD NEW INVENTORY
POST http://localhost:8080/inventory-management/inventory
Content-Type: application/json

{
  "description": "BSNL Project",
  "inventory": {
    "dbType": "MongoDB",
    "dbName": "bsnl_db",
    "hostname": "bsnl9634",
    "port": 27017,
    "username": "bsnlmong",
    "password": "qwqw"
  }
}

### Update INVENTORY
POST http://localhost:8080/inventory-management/inventory
Content-Type: application/json

{
  "projectId": 6,
  "description": "BSNL Project",
  "inventory": {
    "id": 6,
    "dbType": "MongoDB",
    "dbName": "bsnl_db",
    "hostname": "bsnl9634",
    "port": 27017,
    "username": "bsnlmong",
    "password": "qwqw"
  }
}

### Find ALL
GET http://localhost:8080/inventory-management/inventory

### Find By ID
GET http://localhost:8080/inventory-management/inventory/1

### Find By ID ADMIN
GET http://localhost:8080/inventory-management/inventory/admin/1

### DELETE By ID
DELETE http://localhost:8080/inventory-management/inventory/8

### Security
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "TestAdmin",
  "password": "dummy"
}

### Register ADMIN
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "TestAdmin",
  "password": "dummy",
  "roles": [ {"id":  1}]
}

### Register USER
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "TestUser",
  "password": "dummy",
  "roles": [ {"id":  2}]
}

### Users List
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJUZXN0QWRtaW4iLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiZXhwIjoxNjIzMDQ5NjkyLCJpYXQiOjE2MjMwNDYwOTJ9.iVi6kwc5MbyuY_9z_W37JbjDlYremJwmzv_f-t2JqurXEYktOpED1V7W8IPVMX6Ti-EnSyXpZTB6Lhh0WWMv3g